ALTER TABLE users
  ADD COLUMN first_name VARCHAR(255) NULL;

ALTER TABLE users
  ADD COLUMN last_name VARCHAR(255) NULL;

ALTER TABLE users
  ADD COLUMN address VARCHAR(255) NULL;

ALTER TABLE users
  ADD COLUMN zip_code VARCHAR(255) NULL;

ALTER TABLE users
  ADD COLUMN city VARCHAR(255) NULL;

ALTER TABLE users
  ADD COLUMN phones TEXT NULL;