name: 'vepweb'
version: 0.0.1
description: >
  Web application for Voir & Entendre
author: Gaëtan Rizio <gaetan@rizio.fr>
homepage: http://voir-entendre-posso.fr
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  angular: "^1.1.2"
  web_components: ">=0.10.0 <0.11.0"
  browser: any
  klang: ">=0.1.0 <0.2.0"
  jsonx: ">=2.0.0 <3.0.0"
  http: ">=0.11.2 <0.12.0"
  google_maps: ">=2.0.0 <3.0.0"
dev_dependencies:
  unittest: ">=0.11.0+5 <0.12.0"
  mock: ">=0.11.0+2 <0.12.0"
transformers:
- angular:
    html_files: